### ISSUE TITLE
Race condition causes periodic failure to generate html report

### ISSUE THREAD

**Issue by jwtd** [matteofigus/grunt-api-benchmark#3]
I've setup grunt-api-benchmark to generate both the html and json versions of the benchmark results from the same config file. 
```
    api_benchmark: {
      restApi: {
        options: {
          output: 'tests/benchmarks/'
        },
        files: {
          'api-benchmark.html': 'tests/acceptance/api-benchmark.json',
          'api-benchmark.json': 'tests/acceptance/api-benchmark.json'
        }
      }
    }
```
The task always creates the api-benchmark.json file, but sporadicly creates the api-benchmark.html file. When I say "sporadicly", I mean that I can run the task 5 times without changing anything, and a few of the times it will create the html file successfully, and a few times it won't. 

I traced the issue to a [fs.readFile call in api-benchmark](https://github.com/matteofigus/api-benchmark/blob/master/lib/html-converter.js#L15). That call is asynchronous, and it seems to be creating a race condition with the grunt task's code. 

When I change that line to...
```
var template = fs.readFileSync(path.join(__dirname, '../templates/report.html'), 'utf-8');
```
...the html version of the file gets created every single time without fail.

**Comment by matteofigus** [comment]
Good spot, thanks! Can you include here, just for reference, node version you are using, OS and module version (is it the latest one?)

I'll try to have a look later today. 

Thanks
Matteo

**Comment by matteofigus** [comment]
Just published v0.1.1 - Can you try to upgrade an see if it is fixed? :+1:

**Comment by jwtd** [comment]
Node v0.10.35
grunt-api-benchmark v0.1.0

I updated to grunt-api-benchmark@0.1.1, but my task still intermittently fails to generate the html file. This is what I get...
```
jd$ grunt benchmark
Running "api_benchmark:restApi" (api_benchmark) task
Performing benchmarks for file: tests/acceptance/api-benchmark.json
REST api/simpleRoute x 1,265 ops/sec ±1.61% (1000 runs sampled)
REST api/secondaryRoute x 1,185 ops/sec ±2.19% (1000 runs sampled)
REST api/postRoute x 1,623 ops/sec ±1.72% (1000 runs sampled)
REST api/deleteRoute x 1,545 ops/sec ±1.64% (1000 runs sampled)
File "tests/benchmarks/api-benchmark.json" created.

Done, without errors.
```

**Comment by matteofigus** [comment]
Lol, my fault! Can you retry with 0.1.2? :+1:

**Comment by jwtd** [comment]
Both reports are being generated regularly. Seems to be working as expected now. Thanks!

**Comment by matteofigus** [comment]
yay :) closing this. Thanks for your help :+1:
